# Generated by Django 5.1.6 on 2025-03-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField(unique=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slots.appointmentslot')),
            ],
        ),
    ]
